### ISSUE TITLE
This versus CodePlex project?

### ISSUE THREAD

**Issue by daluu** [forcedotcom/windowsphonedriver#1]
This isn't really an issue, but just wanted to clarify/see if this is a separate project than 

https://winphonewebdriver.codeplex.com

or if this is just a mirror of same codebase. As people might be confused with these dual projects.

**Comment by jimevanssfdc** [comment]
This project is entirely unrelated to the one you've referenced. The two projects were developed completely independently of one another.

**Comment by daluu** [comment]
Useful reference for the curious folk, some info pulled/quoted from that other project:

http://winphonewebdriver.codeplex.com/discussions/578727#post1348607

"I think that the main architectural difference between these two projects is that in https://github.com/forcedotcom/windowsphonedriver the driver server is implemented as a command-line executable (run typically on a 'desktop machine') whereas in this project, the driver server is implemented inside the Windows Phone application."

**Comment by daluu** [comment]
Just wanted to mention another interesting project that's kind of related: https://github.com/2gis/Winium
